### PR TITLE
Some Graphical Improvements

### PR DESCRIPTION
**Pull request by yigitkeremoktay**
https://status.theskyfallen.com for a preview.

### CODE REVIEW

**Comment by yigitkeremoktay** [comment]
You can now define a CUSTOM LOGO URL in your config file.

**Comment by yigitkeremoktay** [comment]
Manual Merge of PR https://github.com/Pryx/server-status/pull/114 is completed

**Comment by yigitkeremoktay** [comment]
Debugging revealed an issue with additional copyright text.
Will be fixed in a future commit.

**Comment by yigitkeremoktay** [comment]
All Bugs Fixed. Both of the new features are now fully functional.
Ready to be deployed.

**Comment by Pryx** [comment]
@yigitkeremoktay a lot of the settings would be better to be in the database as we discussed earlier... I don't really want to block merging any PRs because of this anymore, but keep in mind that the settings would need to move at a later time and it might be better to implement it right now :slightly_smiling_face:

**Comment by yigitkeremoktay** [comment]
Are you merging it or not? :)

**Pull request merged**
