### PR TITLE
Implementation of Email & Telegram notification

### PR DESCRIPTION
**Pull request by thnilsen**
Here is the PR requests for email notification. This implements the email notification together with @jhuesser Telegram notification.

I have chosen to keep token for the subscribers in the subscriber table rather than using the tokens table, since the token table is very much linked to the admin users as it is now. This can of course be changed if so desired but would require a way to avoid the overlapping table IDs. 

In addition to the email notification the changes will also add Markdown support for incidents.

The code is working and can be tested on my test server as linked to in #65.

Design of dropdown menu, email and HTML template should be considered work in progress. Help on that part is very much appreciated! 

Install.php has yet to be updated to render settings with the new config.php options.

**Subscriber menu as of now:**
dropdown_menu

**Manage subscription:** (with support for IDN domains!)
subscription

**Email notification:**
status_email

**Telegram notification:**
telegram_message

### CODE REVIEW

**Comment by Chipx0** [comment]
Just how do you set this up? All i get is "ERROR for site owner: Invalid site key" Why do you not provide instructions on how to set this up?

**Comment by Chipx0** [comment]
All i get is a blank page when clicking "subscribe"

**Comment by jhuesser** [comment]
Follow this guide: https://core.telegram.org/widgets/login

**Comment by Chipx0** [comment]
> 
> Follow this guide: https://core.telegram.org/widgets/login
> […](#)
> Am 08.11.2019 um 21:45 schrieb Chipx0 ***@***.***>: ﻿ Just how do you set this up? All i get is "ERROR for site owner: Invalid site key" Why do you not provide instructions on how to set this up? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Im wanting to use the email subscribe, Not the telegram one.

**Comment by yigitkeremoktay** [comment]
@jhuesser and @thnilsen I am starting to work on a new database class which will move some of the settings into database as @Pryx suggested thus allowing this PR to be deployed. Since I could not understand the problem with this PR I will ask you to clarify a few a things.
1. Is this PR functional
2. If it is not what is the issue with it.
Thanks.

**Comment by thnilsen** [comment]
@yigitkeremoktay The PR is functional with the exception of missing the database schema changes since there currently isn't any method to apply db changes automatically. I could also do with some design work on the HTML email template as it is far from good. I'll post a db schema change here later, then we can agree how to implement it.

**Comment by yigitkeremoktay** [comment]
@thnilsen I am trying to implement this as I was creating the database class but I decided not to because it turns out that this not something that I can do without your help as it was impossible to reverse engineer

**Comment by yigitkeremoktay** [comment]
@thnilsen I would be glad if you could help me though 👍

**Comment by thnilsen** [comment]
@yigitkeremoktay  Here is a quick diff. I don't have the time to double check it right now but it should hopefully be correct. Test it and see if it works for you. If not I'll check it later tonight.

[subscription.sql.txt](https://github.com/Pryx/server-status/files/5078605/subscription.sql.txt)

**Comment by yigitkeremoktay** [comment]
@thnilsen I've managed to make it stable enough but see https://skyfallenhosted.ml/ss-demo/ . Your menu is not showing up.

**Comment by thnilsen** [comment]
@yigitkeremoktay Are you still unable to see the subscriber menu? I can see it on all my devices. There's no services added to that instance of server-status so I can't really test the full functionallity, but at least I was able to start the sign up process, get the subscription email and get to the logged in page where one would choose which services to subscribe to.

**Comment by yigitkeremoktay** [comment]
I reverted the CSS update.
See this for the new look update (https://status.theskyfallen.com)

**Comment by yigitkeremoktay** [comment]
I don't have time to work on it for now though :(

**Comment by thnilsen** [comment]
Have you defined the config parameters? At least one of these two needs to be true, otherwise it will not render the menu.

define('SUBSCRIBE_EMAIL', true);
define('SUBSCRIBE_TELEGRAM', true);

**Comment by yigitkeremoktay** [comment]
@thnilsen As we have merged these feature I think you may close this PR as it is now a duplicate

**Comment by thnilsen** [comment]
Closing PR as it is being included via @yigitkeremoktay repo

**Pull request closed without merging**
