### PR TITLE
PHP8 Support

### PR DESCRIPTION
**Pull request by Steffen-MLR**
Hey Guys,
I tried using php8. I did test the following basic functions:
- installation
- login
- add service group & Service
- add incident
- remove incident

i didnt test the subscription feature.

### CODE REVIEW

**Comment by jhuesser** [comment]
thanks for your contribution! When I'm installing for your master branch, somehow the header and footer are missing?

image

**Comment by Steffen-MLR** [comment]
Let me take a look!

**Comment by Steffen-MLR** [comment]
Hi, @jhuesser please take a look at the changes i made. I also added a Dockerfile and docker-compose for rapid testing. This should help speeding things up.

**Comment by Steffen-MLR** [comment]
i tested subscriptions feature and fixed more errors. will merge this now.

**Pull request merged**
